irix:
	(cd SdfastSimul ; make -i -s irix)
	(cd ParticlePointSimul ; make -i -s irix)

linux:
	(cd SdfastSimul ; make -i -s linux)
	(cd ParticlePointSimul ; make -i -s linux)

clean: 
	(cd SdfastSimul ; make -i clean)
	(cd ParticlePointSimul ; make -i clean)
	


