// BEGIN  function prototypes

void skel18init(void);
void skel18state(double timein, double *qin, double *uin);
void skel18qdot(double *oqdot);
void skel18u2qdot(double *uin, double *oqdot);
void skel18psstate(double *lqin);
void skel18dovpk(void);
void skel18doltau(void);
void skel18doiner(void);
void skel18dofs0(void);
void skel18domm(int routine);
void skel18dommldu(int routine);
void skel18lhs(int routine);
void skel18massmat(double (*mmat)[37]);
void skel18frcmat(double *fmat);
void skel18mfrc(double *imult);
void skel18equivht(double *tau);
void skel18fulltrq(double *udotin, double *multin, double *trqout);
void skel18comptrq(double *udotin, double *trqout);
void skel18multtrq(double *multin, double *trqout);
void skel18fs0(void);
void skel18fsmult(void);
void skel18fsfull(void);
void skel18fsgenmult(void);
void skel18fsgenfull(void);
void skel18rhs(void);
void skel18pseudo(double *lqout, double *luout);
void skel18psqdot(double *lqdout);
void skel18psudot(double *ludout);
void skel18perr(double *errs);
void skel18verr(double *errs);
void skel18aerr(double *errs);
int skel18indx(int joint, int axis);
void skel18presacc(int joint, int axis, double prval);
void skel18presvel(int joint, int axis, double prval);
void skel18prespos(int joint, int axis, double prval);
void skel18getht(int joint, int axis, double *torque);
void skel18hinget(int joint, int axis, double torque);
void skel18pointf(int body, double *point, double *force);
void skel18bodyt(int body, double *torque);
void skel18doww(int routine);
void skel18xudot0(int routine, double *oudot0);
void skel18udot0(double *oudot0);
void skel18setudot(double *iudot);
void skel18xudotm(int routine, double *imult, double *oudotm);
void skel18udotm(double *imult, double *oudotm);
void skel18deriv(double *oqdot, double *oudot);
void skel18resid(double *eqdot, double *eudot, double *emults, double *resid);
void skel18mult(double *omults, int *owrank, int *omultmap);
void skel18reac(double (*force)[3], double (*torque)[3]);
void skel18mom(double *lm, double *am, double *ke);
void skel18sys(double *mtoto, double *cm, double (*icm)[3]);
void skel18pos(int body, double *pt, double *loc);
void skel18vel(int body, double *pt, double *velo);
void skel18orient(int body, double (*dircos)[3]);
void skel18angvel(int body, double *avel);
void skel18trans(int frbod, double *ivec, int tobod, double *ovec);
void skel18rel2cart(int coord, int body, double *point, double *linchg, double *rotchg);
void skel18acc(int body, double *pt, double *accel);
void skel18angacc(int body, double *aacc);
void skel18grav(double *gravin);
void skel18mass(int body, double massin);
void skel18iner(int body, double (*inerin)[3]);
void skel18btj(int joint, double *btjin);
void skel18itj(int joint, double *itjin);
void skel18pin(int joint, int pinno, double *pinin);
void skel18pres(int joint, int axis, int presin);
void skel18stab(double velin, double posin);
void skel18getgrav(double *gravout);
void skel18getmass(int body, double *massout);
void skel18getiner(int body, double (*inerout)[3]);
void skel18getbtj(int joint, double *btjout);
void skel18getitj(int joint, double *itjout);
void skel18getpin(int joint, int pinno, double *pinout);
void skel18getpres(int joint, int axis, int *presout);
void skel18getstab(double *velout, double *posout);
void skel18info(int *info);
void skel18jnt(int joint, int *info, int *tran);
void skel18cons(int consno, int *info);
int skel18chkbnum(int routine, int bnum);
int skel18chkjnum(int routine, int jnum);
int skel18chkucnum(int routine, int ucnum);
int skel18chkjaxis(int routine, int jnum, int axnum);
int skel18chkjpin(int routine, int jnum, int pinno);
void skel18st2ang(double *st, double *stang);
void skel18ang2st(double *stang, double *st);
void skel18nrmsterr(double *st, double *normst, int routine);
void skel18normst(double *st, double *normst);
void skel18gentime(int *gentm);

// END of /homes/a/pfal/danceMulti/sdfastObjs/skel18/skel18_dyn.c function prototypes.

