irix:
	(cd ArticulatedObject ; make -i -s irix)
	(cd ParticlePointSystem ; make -i -s irix)

linux:
	(cd ArticulatedObject ; make -i -s linux)
	(cd ParticlePointSystem ; make -i -s linux)

clean: 
	(cd ArticulatedObject ; make -i clean)
	(cd ParticlePointSystem ; make -i clean)
	


